title: Mega Big News
author:
  name: Mega Big News
  email: megabignews@gmail.com
description: |
  Newsing all over you.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
  - disclaimer.md
# Number of articles shown per page. Change this value to adjust pagination.
articles_per_page: 20
minima:
  skin: auto
google_analytics: G-L7R80M8SCM
url: https://megabignews.com
baseurl: ""